/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Peter
 */
public class updateinfo extends javax.swing.JFrame {

    /**
     * Creates new form updateinfo
     */
    public updateinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 40, 120, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(250, 40, 120, 30);

        jTextField2.setText("0");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(250, 80, 120, 30);

        jTextField3.setText("dd/mm/yy");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(250, 120, 120, 30);

        jRadioButton1.setText("male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(240, 170, 60, 23);

        jRadioButton2.setText("female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(320, 170, 70, 23);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(250, 210, 130, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(250, 250, 130, 30);

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(250, 300, 130, 30);

        jLabel2.setText("Age");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 90, 120, 20);

        jLabel3.setText("DOB");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 130, 60, 20);

        jLabel4.setText("Sex");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 170, 50, 20);

        jLabel5.setText("Fathers's name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 220, 110, 20);

        jLabel6.setText("Section");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 260, 70, 20);

        jLabel7.setText("Contact number");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 300, 120, 30);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(280, 373, 80, 30);

        jButton2.setText("Go back");
        jButton2.setActionCommand("Goback");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(110, 373, 71, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 60, 490, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
             sex="male";
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        frame2 f2=new frame2();
        f2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
               if(!(Character.isDigit(c)||c=='/')||(c==KeyEvent.VK_BACKSPACE)||c==KeyEvent.VK_DELETE)
               {
                   evt.consume();
                   //JOptionPane.showMessageDialog(null,"Invalid number");
               }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
char c=evt.getKeyChar();
               if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE)||c==KeyEvent.VK_DELETE)
               {
                   evt.consume();
                   //JOptionPane.showMessageDialog(null,"Invalid number");
               }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyTyped
    String sex;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name=jTextField1.getText(),dat=jTextField3.getText(),fname=jTextField4.getText(),section=jComboBox1.getSelectedItem().toString(),contact=jTextField5.getText();
        int age=Integer.parseInt(jTextField2.getText());
          ResultSet rs;
          Statement st = null;
          String usn=frame1.jTextField1.getText();
         
          try{
              Connection con;
          
            Class.forName("org.apache.derby.jdbc.ClientDriver");
                  con = DriverManager.getConnection("jdbc:derby://localhost:1527/javaproject","root","root123");
             st=con.createStatement();
             
        int s=0;
        if(!name.equals(""))
        {
             s=st.executeUpdate("update STUDENT set NAME='"+name+"' where usn='"+usn+"'");
        }
          if(age!=0)
        {
             s=st.executeUpdate("update STUDENT set AGE="+age+" where usn='"+usn+"'");
        }  if(!dat.equals("dd/mm/yy"))
        {
             s=st.executeUpdate("update STUDENT set DOB='"+dat+"' where usn='"+usn+"'");
        }  if(!sex.equals(""))
        {
             s=st.executeUpdate("update STUDENT set SEX='"+sex+"' where usn='"+usn+"'");
        } 
        if(!fname.equals(""))
        {
             s=st.executeUpdate("update STUDENT set F_NAME='"+fname+"' where usn='"+usn+"'");
        } if(!section.equals(""))
        {
             int r=st.executeUpdate("update STUDENT set SECTION='"+section+"' where usn='"+usn+"'");
        }
         if(!contact.equals(""))
        {
             s=st.executeUpdate("update STUDENT set CONTACT='"+contact+"' where usn='"+usn+"'");
        }
        if(s==0)
        {
            JOptionPane.showMessageDialog(null,"Please enter valid input");
        }
        else
        {
             JOptionPane.showMessageDialog(null,"Successfully updated");
             setVisible(false);
             frame2 f2=new frame2();
             f2.setVisible(true);
        }
        
          } 
          catch (ClassNotFoundException ex) {
            Logger.getLogger(updateinfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(updateinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       sex="female";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
